pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'my-app:latest'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'be',
                    url: 'https://lab.ssafy.com/s11-webmobile1-sub2/S11P12E108.git',
                    credentialsId: 'testttt' // Jenkins 자격 증명 ID
            }
        }

        stage('Build') {
            steps {
                dir('be-spring/iscode/iscode') {
                    script {
                        def gradleHome = tool name: 'gradle', type: 'gradle'
                            sh 'chmod 777 gradlew'
                            sh './gradlew bootJar'
                    }
                }
            }
        }
        stage('Archive') {
            steps {
                dir('be-spring/iscode/iscode') {
                    archiveArtifacts artifacts: '**/build/libs/*.jar', allowEmptyArchive: true
                }
            }
        }
    }
}
