pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'be-compiler'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'infra-be/compiler',
                    url: 'https://lab.ssafy.com/s11-webmobile1-sub2/S11P12E108.git',
                    credentialsId: 'Be' // Jenkins 자격 증명 ID
            }
        }

        stage('Build') {
            steps {
                dir('be-spring/iscode/iscode') {
                    script {
                        def gradleHome = tool name: 'Cokkiri-gradle', type: 'gradle'
                            sh 'chmod 777 gradlew'
                            sh './gradlew bootJar'
                    }
                }
            }
        }
        stage('Archive') {
            steps {
                dir('be-spring/iscode/iscode') {
                    archiveArtifacts artifacts: '**/build/libs/*.jar', allowEmptyArchive: true
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('be-spring'){
                    script {
                        sh 'docker build -t ${DOCKER_IMAGE} .'
                    }
                }
            }
        }


    }
}
