pipeline {
    agent any

    environment {

        DOCKER_IMAGE = 'ohuggy/fe_test'
        DOCKER_HUB = 'dockerhub' // Jenkins 자격 증명 ID
//         PATH = "/usr/local/bin"
    }

    stages {
        
        stage('Checkout') {
            steps {
                git branch: 'infra-fe/deploy',
                    url: 'https://lab.ssafy.com/s11-webmobile1-sub2/S11P12E108.git',
                    credentialsId: 'Be' // Jenkins 자격 증명 ID
            }
        }

        stage("Install Dependencies"){
            steps{
                dir("fe-vue"){
                    script{
                        // Node.js 설치 확인 및 종속성 설치
                        sh 'node -v'
                        sh 'npm -v'
                        sh 'npm install'
                    }

                }
            }
        }

        stage('Build') {
            steps {
                dir('fe-vue') {
                    script {
                      sh 'npm run build'
                    }
                }
            }
        }

    //     stage('Build Docker Image') {
    //         steps {
    //             script {
    //                 // 빌드된 정적 파일을 포함하여 Docker 이미지를 빌드
    //                 sh 'docker build -t ${DOCKER_IMAGE} -f fe-vue/Dockerfile .'
    //             }
    //         }
    //     }

    //     stage('Push Docker Image to Docker Hub') {
    //         steps {
    //             script {
    //                 docker.withRegistry('https://index.docker.io/v1/', env.DOCKER_HUB) {
    //                     // Docker 이미지 푸시
    //                     sh 'docker push ${DOCKER_IMAGE}'
    //                 }
    //             }
    //         }
    //     }

    //     stage('Deploy Docker Container with docker compose'){
    //         steps{
    //             script{
    //                 dir("fe-vue"){
    //                     // Docker Compose 실행 전에 기존 컨테이너를 종료 및 제거
    //                     sh 'docker-compose down'
    //                     // Docker Compose를 사용하여 서비스 빌드 및 실행
    //                     sh 'docker-compose up --build -d'
    //                 }

    //             }
    //         }
    //     }
    // }

    // post {
    //     always {
    //         script {
    //             // Cleanup: Docker Hub에서 로그아웃
    //             sh 'docker logout'
    //         }
    //     }
    }
}
